/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export interface JsonObject {
  [x: string]: JsonValue | undefined;
}

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CalculatedTrackStats {
  ascent_calc: number | null;
  length_calc: number | null;
  speed_calc: number | null;
  timelength_calc: number | null;
  track_id: number | null;
}

export interface CalculatedTrackStatsTmp {
  ascent_calc: number | null;
  length_calc: number | null;
  speed_calc: number | null;
  timelength_calc: number | null;
  track_id: number | null;
}

export interface Config {
  conftype: string;
  id: Generated<number>;
  key: string;
  value: string;
}

export interface PublicCredAuthenticators {
  counter: Int8;
  creationdate: Timestamp;
  credentialbackedup: boolean;
  credentialdevicetype: string;
  credentialid: string;
  credentialpublickey: Buffer;
  transports: string;
  userid: string;
}

export interface PublicGeographyColumns {
  coord_dimension: number | null;
  f_geography_column: string | null;
  f_table_catalog: string | null;
  f_table_name: string | null;
  f_table_schema: string | null;
  srid: number | null;
  type: string | null;
}

export interface PublicGeometryColumns {
  coord_dimension: number | null;
  f_geometry_column: string | null;
  f_table_catalog: string | null;
  f_table_name: string | null;
  f_table_schema: string | null;
  srid: number | null;
  type: string | null;
}

export interface PublicRegistrationKeys {
  created: Generated<Timestamp>;
  regkey: Generated<string>;
  used: Generated<boolean>;
  username: string;
}

export interface PublicSession {
  expire: Timestamp;
  sess: Json;
  sid: string;
}

export interface PublicSpatialRefSys {
  auth_name: string | null;
  auth_srid: number | null;
  proj4text: string | null;
  srid: number;
  srtext: string | null;
}

export interface Segments {
  track_id: number | null;
  track_segment_id: number;
}

export interface TmMetaSchemaSid {
  schema: string;
  sid: string;
}

export interface TrackPoints {
  elevation: number | null;
  id: Generated<number>;
  point_time: Timestamp | null;
  segment_point_id: number;
  track_id: number | null;
  track_segment_id: number;
  wkb_geometry: string | null;
}

export interface TrackPointsTmp {
  elevation: number | null;
  id: Generated<number>;
  point_time: Timestamp | null;
  segment_point_id: number;
  track_id: number | null;
  track_segment_id: number;
  wkb_geometry: string | null;
}

export interface Tracks {
  ascent: number | null;
  ascent_calc: number | null;
  hash: string | null;
  id: number;
  length: number | null;
  length_calc: number | null;
  name: string | null;
  src: string | null;
  time: Timestamp | null;
  timelength: number | null;
  timelength_calc: number | null;
  wkb_geometry: string | null;
}

export interface DB {
  calculated_track_stats: CalculatedTrackStats;
  calculated_track_stats_tmp: CalculatedTrackStatsTmp;
  config: Config;
  "public.cred_authenticators": PublicCredAuthenticators;
  "public.geography_columns": PublicGeographyColumns;
  "public.geometry_columns": PublicGeometryColumns;
  "public.registration_keys": PublicRegistrationKeys;
  "public.session": PublicSession;
  "public.spatial_ref_sys": PublicSpatialRefSys;
  segments: Segments;
  "tm_meta.schema_sid": TmMetaSchemaSid;
  track_points: TrackPoints;
  track_points_tmp: TrackPointsTmp;
  tracks: Tracks;
}
