/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EditableText: typeof import('./src/components/EditableText.vue')['default']
    FilteredMap: typeof import('./src/components/FilteredMap.vue')['default']
    FilteredTrackList: typeof import('./src/components/FilteredTrackList.vue')['default']
    IBiArrowDownCircleFill: typeof import('~icons/bi/arrow-down-circle-fill')['default']
    IBiArrowLeft: typeof import('~icons/bi/arrow-left')['default']
    IBiArrowRightCircle: typeof import('~icons/bi/arrow-right-circle')['default']
    IBiChevronRight: typeof import('~icons/bi/chevron-right')['default']
    IBiIconTrash: typeof import('~icons/bi/icon-trash')['default']
    IBiPencilFill: typeof import('~icons/bi/pencil-fill')['default']
    IBiTrash: typeof import('~icons/bi/trash')['default']
    MapComponent: typeof import('./src/components/MapComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrackCard: typeof import('./src/components/TrackCard.vue')['default']
    TrackManagerNavBar: typeof import('./src/components/TrackManagerNavBar.vue')['default']
    TrackOverview: typeof import('./src/components/TrackOverview.vue')['default']
    TrackSection: typeof import('./src/components/TrackSection.vue')['default']
    UploadItem: typeof import('./src/components/UploadItem.vue')['default']
  }
}
