/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthOrchestrator: typeof import('./src/components/auth/AuthOrchestrator.vue')['default']
    DropField: typeof import('./src/components/DropField.vue')['default']
    EditableText: typeof import('./src/components/EditableText.vue')['default']
    ErrorIndicator: typeof import('./src/components/ErrorIndicator.vue')['default']
    IBiArrowDownCircleFill: typeof import('~icons/bi/arrow-down-circle-fill')['default']
    IBiArrowLeft: typeof import('~icons/bi/arrow-left')['default']
    IBiArrowRightCircle: typeof import('~icons/bi/arrow-right-circle')['default']
    IBiCheck2: typeof import('~icons/bi/check2')['default']
    IBiChevronRight: typeof import('~icons/bi/chevron-right')['default']
    IBiClipboard: typeof import('~icons/bi/clipboard')['default']
    IBiCompassFill: typeof import('~icons/bi/compass-fill')['default']
    IBiExclamationTriangleFill: typeof import('~icons/bi/exclamation-triangle-fill')['default']
    IBiPencilFill: typeof import('~icons/bi/pencil-fill')['default']
    IBiTrash: typeof import('~icons/bi/trash')['default']
    LoginFailureModal: typeof import('./src/components/auth/LoginFailureModal.vue')['default']
    LogoutForm: typeof import('./src/components/auth/LogoutForm.vue')['default']
    MapComponent: typeof import('./src/components/MapComponent.vue')['default']
    RegistrationModal: typeof import('./src/components/auth/RegistrationModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionExpiredModal: typeof import('./src/components/auth/SessionExpiredModal.vue')['default']
    TrackCard: typeof import('./src/components/TrackCard.vue')['default']
    TrackManagerNavBar: typeof import('./src/components/TrackManagerNavBar.vue')['default']
    TrackSection: typeof import('./src/components/TrackSection.vue')['default']
    UploadItem: typeof import('./src/components/UploadItem.vue')['default']
  }
}
