/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DropField: typeof import('./src/components/DropField.vue')['default']
    EditableText: typeof import('./src/components/EditableText.vue')['default']
    FilteredMap: typeof import('./src/components/FilteredMap.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    LogoutForm: typeof import('./src/components/auth/LogoutForm.vue')['default']
    MapComponent: typeof import('./src/components/MapComponent.vue')['default']
    RegistrationForm: typeof import('./src/components/auth/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrackCard: typeof import('./src/components/TrackCard.vue')['default']
    TrackManagerNavBar: typeof import('./src/components/TrackManagerNavBar.vue')['default']
    TrackSection: typeof import('./src/components/TrackSection.vue')['default']
    UploadItem: typeof import('./src/components/UploadItem.vue')['default']
  }
}
